### ISSUE TITLE
[BUG] WechatPay.php 模块 sign 签名方法的 strtoupper 应该改为 strtolower

### ISSUE THREAD

**Issue by huliuqing** [zhangv/wechat-pay#5]
**生成的签名需小写**

详见 [微信签名算法文档](https://mp.weixin.qq.com/wiki?action=doc&id=mp1421141115&t=0.25897372489233417#62)

**Comment by zhangv** [comment]
请参考：https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=4_3

> 第二步，在stringA最后拼接上key得到stringSignTemp字符串，并对stringSignTemp进行MD5运算，再将得到的字符串所有字符转换为大写，得到sign值signValue。
